Repository pasqal-io/qadence2-expressions, pull requests merged in 2024-11, with the labels that each got.

#29 [Infra] Add remove unneeded version cap on Python version and update notebook to latest syntax
  examples/examples.ipynb
  pyproject.toml
Labels: infra

#30 [Testing, Infra] Add hypothesis
  .pre-commit-config.yaml
  pyproject.toml
  qadence2_expressions/__init__.py
  qadence2_expressions/core/__init__.py
  qadence2_expressions/core/constructors.py
  qadence2_expressions/core/expression.py
  qadence2_expressions/functions.py
  qadence2_expressions/ircompiler.py
  qadence2_expressions/operators.py
  renovate.json
  tests/strategies.py
  tests/test_constructors.py
  tests/test_environment.py
  tests/test_expression.py
  tests/test_functions.py
  tests/test_ir_compilation.py
  tests/test_support.py
Labels: infra, testing

#32 [Bug] Fix failing test due to Environment resetting.
  tests/test_environment.py
  tests/test_ir_compilation.py
Labels: bug

#34 [Docs] Populate docs.
  README.md
  docs/api/constructors.md
  docs/api/environment.md
  docs/api/expressions.md
  docs/api/support.md
  docs/contents/expression_system.md
  docs/contents/ir_compilation.md
  docs/contents/useful_functions.md
  docs/extras/css/colors.css
  docs/extras/css/home.css
  docs/extras/css/mkdocstrings.css
  docs/extras/overrides/home.html
  docs/getting_started/CONTRIBUTING.md
  docs/getting_started/LICENSE.md
  docs/getting_started/installation.md
  docs/index.md
  docs/sample_page.md
  docs/tutorials/index.md
  mkdocs.yml
  qadence2_expressions/core/constructors.py
  qadence2_expressions/core/environment.py
  qadence2_expressions/core/expression.py
  qadence2_expressions/core/support.py
Labels: documentation

#35 [Docs] Bump patch for docs release.
  pyproject.toml
Labels: documentation

#37 [Feature] Add the Hadamard and SWAP gates to the Hermitian operators list
  qadence2_expressions/__init__.py
  qadence2_expressions/core/expression.py
  qadence2_expressions/operators.py
  tests/test_operators.py
Labels: feature
